#!/bin/bash
#
# usage: cut-release version# [make-args...]
#

function isthatright {
  echo -n "Does that look right? [y/n] "
  while read yn; do
    if [ "$yn" = y -o "$yn" = Y -o "$yn" = yes -o "$yn" = YES -o "$yn" = Yes ]; then
      break
    elif [ "$yn" = n -o "$yn" = N -o "$yn" = no -o "$yn" = NO -o "$yn" = No ]; then
      echo "Aborting as per user request." >&2
      exit 1
    fi
  done
}

if [ $# -lt 1 ]; then
  echo "Usage: $(basename "$0") version-designation [make-args...]" >&2
  exit 1
fi

if ! [ -e src/expr/node.h -a -e .svn ]; then
  echo "$(basename "$0"): ERROR: you should run this from the top-level of a CVC4 subversion working directory" >&2
  exit 1
fi

version="$1"
shift

if echo "$version" | grep '[^a-zA-Z0-9_.+(){}^%#-]' &>/dev/null; then
  echo "$(basename "$0"): ERROR: version designation \`$version' contains illegal characters" >&2
  exit 1
fi

if ! svn ls "https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version" 2>&1 >/dev/null | grep non-existent >/dev/null; then
  echo "$(basename "$0"): ERROR: subversion repo already contains a release \`$version'" >&2
  exit 1
fi

if [ -n "$(svn status -q)" ]; then
  echo "$(basename "$0"): ERROR: \"svn status\" indicates there are local modifications; please commit first" >&2
  exit 1
fi

echo "Please take a moment to run the following command:"
root="$(svn info | grep "^Repository Root: https://subversive.cims.nyu.edu/.*" | cut -f3 -d' ')"
if [ -z "$root" ]; then
  echo "$(basename "$0"): ERROR: can't get repository root URL" 2>&1
  exit 1
fi

if ! grep '^m4_define(_CVC4_RELEASE_STRING, \[.*\])' configure.ac &>/dev/null; then
  echo "$(basename "$0"): ERROR: cannot locate the RELEASE_STRING line of configure.ac" >&2
  exit 1
fi
perl -pi -e 's/^m4_define\(_CVC4_RELEASE_STRING, \[.*\]\)/m4_define(_CVC4_RELEASE_STRING, ['"$version"'])/' configure.ac

trap 'echo; echo; svn revert configure.ac; echo' EXIT

echo
echo 'Made the following change to configure.ac:'
echo
svn diff configure.ac
echo
isthatright

if ! grep '^m4_define(_CVC4_RELEASE_STRING, \['"$version"'\])' configure.ac &>/dev/null; then
  echo "$(basename "$0"): INTERNAL ERROR: cannot find the modified RELEASE_STRING line in configure.ac, bailing..." >&2
  exit 1
fi
if [ -z "$(svn status -q configure.ac)" ]; then
  echo "$(basename "$0"): INTERNAL ERROR: \"svn status\" indicates there are no local modifications to configure.ac; I expected the one I just made!" >&2
  exit 1
fi

set -ex

./autogen.sh
./configure production-cln-staticbinary --disable-shared
make dist "$@"
(cd builds
tar xf "cvc4-$version.tar.gz"
cd "cvc4-$version"
./configure production-cln-staticbinary --disable-shared
#make check "$@"
#make distcheck "$@"
)

set +ex

echo
echo 'This release of CVC4 will identify itself as:'
echo
builds/cvc4-$version/builds/bin/cvc4 --version
echo
isthatright

echo
echo 'This binary release of CVC4 will identify itself as being configured like this:'
echo
builds/cvc4-$version/builds/bin/cvc4 --version
echo
isthatright

echo
echo "Signing tarball..."
cp -p "builds/cvc4-$version.tar.gz" .
gpg -b --armor "cvc4-$version.tar.gz"

echo
echo "Signing binary..."
cp -p "builds/cvc4-$version/builds/bin/cvc4" "cvc4-$version"
gpg -b --armor "cvc4-$version"

echo
echo "About to run: svn commit -m \"Cutting release $version.\""
isthatright
: svn commit -m "Cutting release $version."

echo
echo "About to run: svn copy -m \"Cutting release $version.\" \"$root\" \"https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version\""
isthatright
: svn copy -m "Cutting release $version." "$root" "https://subversive.cims.nyu.edu/cvc4/cvc4/tags/releases/$version"
